#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true) {
		motor[frontLeft] = (vexRT[Ch2] - vexRT[Ch4]);
		motor[backLeft] = (vexRT[Ch2] - vexRT[Ch4]);
		motor[frontRight] = (-1*vexRT[Ch2] - vexRT[Ch4]);
		motor[backRight] = (-1*vexRT[Ch2] - vexRT[Ch4]);
	}



}
