#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Motor,  port1,           pusherright,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftback,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftmid,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftfront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightback,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightmid,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightfront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intakeright,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           intakeleft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          pusherleft,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		motor[intakeleft] = 0;
		motor[intakeright] = 0;
		motor[pusherleft] = 0;
		motor[pusherright] = 0;

		motor[leftfront] = vexRT[Ch3] + vexRT[Ch1];
		motor[leftmid] = vexRT[Ch3] + vexRT[Ch1];
		motor[leftback] = vexRT[Ch3] + vexRT[Ch1];

		motor[rightfront] = -vexRT[Ch3] + vexRT[Ch1];
		motor[rightmid] = -vexRT[Ch3] + vexRT[Ch1];
		motor[rightback] = -vexRT[Ch3] + vexRT[Ch1];

		//motor[pusher] = -vexRT[Ch2Xmtr2];

		if(SensorValue[limit] == 1){
			motor[pusherleft] = 0;
			motor[pusherright] = 0;
		}

		while(vexRT[Btn5UXmtr2]){
			motor[intakeleft] = 127;
			motor[intakeright] = 127;
		}
		while(vexRT[Btn6UXmtr2]){
			motor[intakeleft] = -127;
			motor[intakeright] = -127;
		}
		while(vexRT[Btn8UXmtr2]){
			motor[pusherleft] = -127;
			motor[pusherright] = -127;
		}
		while (vexRT[Btn8DXmtr2]){
			motor[pusherleft] = 127;
			motor[pusherright] = 127;
		}
	}
}
