#pragma config(Sensor, dgtl1,  armPos,         sensorQuadEncoder)
#pragma config(Motor,  port1,           armRight,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           midRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           midLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           stackPusher,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          armLeft,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*

*Plz edit after changes*
Date Created: Oct 25 2019
Last Edited by: Zayeed Ghori
Date Last Edited: Nov 28 2019

*/

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void tankDrive(){
	// Tank
	// These functions control motor values (clockwise +, counter -) based on joystick input (2 and 3)
	motor[frontLeft] = vexRT[Ch3];
	motor[frontRight] = -vexRT[Ch2];
	motor[backLeft] = vexRT[Ch3];
	motor[backRight] = -vexRT[Ch2];
}

void arcadeDrive(){
	// Arcade
	// These functions control motor values (clockwise +, counter -) based on joystick input (1 and 3)

	// Padding for insignificant input from the joystick
	if ((vexRT[Ch3] <= 5 && vexRT[Ch3] >= -5) && (vexRT[Ch1] <= 5 && vexRT[Ch1] >= -5)){
		motor[frontLeft] = 0;
		motor[midLeft] = 0;
		motor[backLeft] = 0;
		motor[frontRight] = 0;
		motor[midRight] = 0;
		motor[backRight] = 0;
	}

	// Regular joystick input
	else{
		motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1];
		motor[midLeft] = -vexRT[Ch3] - vexRT[Ch1];
		motor[backLeft] = -vexRT[Ch3] - vexRT[Ch1];
		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1];
		motor[midRight] = vexRT[Ch3] - vexRT[Ch1];
		motor[backRight] = -vexRT[Ch3] + vexRT[Ch1];
	}
}

// This function is the test function for the driver remote to have ghost power and prevent the arms from falling due to gravity
void ghostPower(int left, int right){
	while (!vexRT[Btn5D] && !vexRT[Btn5U]) {
		motor[armLeft] = left;
		motor[armRight] = right;
	}
}

// This function moves the arms of the robot based on Ch3 value on the Op controller
void armControl(){
	//TEST
	//if (vexRT[Btn5U] && !vexRT[Btn5D]){
	//	motor[armLeft] = -127;
	//  motor[armRight] = 127;
	//}
	//else if (!vexRT[Btn5U] && vexRT[Btn5D]){
	//	motor[armLeft] = 127;
	//  motor[armRight] = -127;
	//}
	//else{
	//	motor[armLeft] = 0;
	//	motor[armRight] = 0;
	//}

	motor[armLeft] = -vexRT[Ch3Xmtr2];
	motor[armRight] = vexRT[Ch3Xmtr2];
}

// This function brings the arms into the short lock position
void armLockLow(){
	motor[armLeft] = -127;
	motor[armRight]= 127;
}

// This function brings the arm into the high lock position
void armLockHigh(){
	motor[armLeft] = -127;
	motor[armRight]= 127;
}

// This function controls the intake motors based on 6D and 6U button values on the driver controller
void intakeSucc(){
	// Padding/Ghost power
	if (vexRT[Ch2Xmtr2] <= 5 && vexRT[Ch2Xmtr2] >= -5){
		motor[intake] = 0;
	}
	else{
		motor[intake] = -vexRT[Ch2Xmtr2];
	}
}

int incrementButtonCount(bool buttonPressed, int numOfPresses){
	if (buttonPressed){
		numOfPresses++;
	}

	int mode = numOfPresses % 2;
	return mode;
}

void stackControl(){
	// Push
	//int mode = incrementButtonCount(vexRT[Btn7DXmtr2], buttonPushes);
	if(vexRT[Btn6U]) {
			motor[stackPusher] = 65;//change back to full if needed
			motor[intake] = -20;
			motor[intake] = 0
	}
	else if(vexRT[Btn6D]){
			motor[stackPusher] = -65;
			motor[intake] = 20;
			motor[intake] = 0;
}
	// Resets the motor values to 0 if none of the if statements run
	else{
		motor[stackPusher] = 0;
	}
}

// Auto
void moveForward(int speed){
		motor[frontLeft] = speed;
		motor[midLeft] = -speed;
		motor[backLeft] = -speed;
		motor[frontRight] = speed;
		motor[midRight] = speed;
		motor[backRight] = -speed;
}

void moveBackward(int speed){
		motor[frontLeft] = -speed;
		motor[midLeft] = speed;
		motor[backLeft] = speed;
		motor[frontRight] = -speed;
		motor[midRight] = -speed;
		motor[backRight] = speed;
}

void turnRight(int speed){
		motor[frontLeft] = speed;
		motor[midLeft] = -speed;
		motor[backLeft] = -speed;
		motor[frontRight] = -speed;
		motor[midRight] = -speed;
		motor[backRight] = speed;
}

void turnLeft(int speed){
		motor[frontLeft] = -speed;
		motor[midLeft] = speed;
		motor[backLeft] = speed;
		motor[frontRight] = speed;
		motor[midRight] = speed;
		motor[backRight] = -speed;
}

void resetBaseMotors(){
		motor[frontLeft] = 0;
		motor[midLeft] = 0;
		motor[backLeft] = 0;
		motor[frontRight] = 0;
		motor[midRight] = 0;
		motor[backRight] = 0;
}

void intakeIn(int speed){
	motor[intake] = speed;
}

void intakeOut(int speed){
	motor[intake] = -speed;
}

void resetIntake(){
	motor[intake] = 0;
}

void armUp(){
	motor[armLeft] = -127;
	motor[armRight] = 127;
}

void armDown(){
	motor[armLeft] = 60;
	motor[armRight] = -60;
}

void resetArmMotors(){
	motor[armLeft] = 0;
	motor[armRight] = 0;
}

void stackOut(){
	motor[stackPusher] = 127;
	motor[intake] = -20;
}

void stackIn(){
	motor[stackPusher] = -127;
	motor[intake] = 20;
}

void resetStackMotors(){
	motor[stackPusher] = 0;
	motor[intake] = 0;
}

void autoBlue(){
	resetBaseMotors();
	armUp();
	wait1Msec(600);

	armDown();
	wait1Msec(200);

	resetArmMotors();

	moveForward(65);
	intakeIn(127);
	wait1Msec(1700);

	resetBaseMotors();
	wait1Msec(1000);
	resetIntake();

	moveBackward(65);
	wait1Msec(1700);

	turnRight(65);
	wait1Msec(600);

	moveForward(65);
	wait1Msec(800);

	resetBaseMotors();

	stackOut();
	wait1Msec(800);

	resetStackMotors();

	intakeOut(50);
	wait1Msec(500);
	moveBackward(65);
	resetIntake();

	wait1Msec(700);

	resetBaseMotors();
}

void autoRed(){

}

int baseMotors[6] = {motor[frontLeft],
		motor[midLeft],
		motor[backLeft],
		motor[frontRight],
		motor[midRight],
		motor[backRight]
		};

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	SensorValue[armPos] = 0;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	autoBlue();


}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	while(true){
		arcadeDrive();
		armControl();
		intakeSucc();
		stackControl();
}
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
  }
