#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Sensor, dgtl2,  limit2,         sensorTouch)
#pragma config(Motor,  port1,           pusherRight,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           midLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           midRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intakeRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           intakeLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          pusherLeft,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

*Plz edit after changes*
Date Created: Oct 25 2019
Last Edited by: Zayeed Ghori
Date Last Edited: Nov 29 2019

*/

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void arcadeDrive(){
	// Arcade
	// These functions control motor values (clockwise +, counter -) based on joystick input (1 and 3)
		motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1];
		motor[midLeft] = vexRT[Ch3] + vexRT[Ch1];
		motor[backLeft] = vexRT[Ch3] + vexRT[Ch1];

		motor[frontRight] = -vexRT[Ch3] + vexRT[Ch1];
		motor[midRight] = -vexRT[Ch3] + vexRT[Ch1];
		motor[backRight] = -vexRT[Ch3] + vexRT[Ch1];
}

void pushStack(){
	if(vexRT[Btn8UXmtr2]){
		motor[pusherleft] = -127;
		motor[pusherright] = -127;
	}
	else if (vexRT[Btn8DXmtr2]){
		motor[pusherleft] = 127;
		motor[pusherright] = 127;
	}
}

void intakeSucc(){
	if(vexRT[Btn5UXmtr2]){
		motor[intakeleft] = 127;
		motor[intakeright] = 127;
	}
	else if(vexRT[Btn6UXmtr2]){
		motor[intakeleft] = -127;
		motor[intakeright] = -127;
	}
	else{
		motor[intakeleft] = 0;
		motor[intakeright] = 0;
	}
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

		//Main loop
		while (true)
		{
		motor[intakeLeft] = 0;
		motor[intakeRight] = 0;
		motor[pusherLeft] = 0;
		motor[pusherRight] = 0;

		motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1];
		motor[midLeft] = vexRT[Ch3] + vexRT[Ch1];
		motor[backLeft] = vexRT[Ch3] + vexRT[Ch1];

		motor[frontRight] = -vexRT[Ch3] + vexRT[Ch1];
		motor[midRight] = -vexRT[Ch3] + vexRT[Ch1];
		motor[backRight] = -vexRT[Ch3] + vexRT[Ch1];

		motor[pusherleft] = -vexRT[Ch2Xmtr2];
		motor[pusherright] = vexRT[Ch2Xmtr2];

		if(SensorValue[limit] == 1){
			motor[pusherleft] = 0;
			motor[pusherright] = 0;
		}

		while(vexRT[Btn5UXmtr2]){
			motor[intakeLeft] = 127;
			motor[intakeRight] = 127;
		}
		while(vexRT[Btn6UXmtr2]){
			motor[intakeLeft] = -127;
			motor[intakeRight] = -127;
		}
		while(vexRT[Btn8UXmtr2]){
			motor[pusherLeft] = -127;
			motor[pusherRight] = -127;
		}
		while (vexRT[Btn8DXmtr2]){
			motor[pusherLeft] = 127;
			motor[pusherRight] = 127;
		}
		}

    // Remove this function call once you have "real" code.
  }
