#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           midLeftOne,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           midLeftTwo,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           midRightOne,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           midRightTwo,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backRight,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

*Plz edit after changes*
Date Created: Nov 29 2019
Last Edited by: Zayeed Ghori
Date Last Edited: Nov 29 2019

*/
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void arcadeDrive(){
	// Arcade
	// These functions control motor values (clockwise +, counter -) based on joystick input (1 and 3)
		motor[frontLeft] = -vexRT[Ch1] - vexRT[Ch3];
		motor[midLeftOne] = -vexRT[Ch1] - vexRT[Ch3];
		motor[midLeftTwo] = -vexRT[Ch1] - vexRT[Ch3];
		motor[backLeft] = -vexRT[Ch1] - vexRT[Ch3];
		motor[frontRight] = -vexRT[Ch1] + vexRT[Ch3];
		motor[midRightOne] = -vexRT[Ch1] + vexRT[Ch3];
		motor[midRightTwo] = -vexRT[Ch1] + vexRT[Ch3];
		motor[backRight] = -vexRT[Ch1] + vexRT[Ch3];
}

void moveForward(int speed){
		motor[frontLeft] = -speed;
		motor[midLeftOne] = -speed;
		motor[midLeftTwo] = -speed;
		motor[backLeft] = -speed;
		motor[frontRight] = speed;
		motor[midRightOne] = speed;
		motor[midRightTwo] = speed;
		motor[backRight] = speed;
}

void moveBackward(int speed){
		motor[frontLeft] = speed;
		motor[midLeftOne] = speed;
		motor[midLeftTwo] = speed;
		motor[backLeft] = speed;
		motor[frontRight] = -speed;
		motor[midRightOne] = -speed;
		motor[midRightTwo] = -speed;
		motor[backRight] = -speed;
}

void turnRight(int speed){

}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // This is the main execution loop for the user control program.
  // Each time through the loop your program should update motor + servo
  // values based on feedback from the joysticks.

  // ........................................................................
  // Insert user code here. This is where you use the joystick values to
  // update your motors, etc.
  // ........................................................................

	//Main Loop
	while(true)
	{
		arcadeDrive();
	}
  // Remove this function call once you have "real" code.
  UserControlCodePlaceholderForTesting();
}
