#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           intakeRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intakeLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armRight,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

*Plz edit after changes*
Date Created: Oct 25 2019
Last Edited by: Zayeed Ghori
Date Last Edited: Nov 30 2019

*/
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void arcadeDrive(){
	motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1];
	motor[backLeft] = vexRT[Ch3] + vexRT[Ch1];
	motor[frontRight] = -vexRT[Ch3] + vexRT[Ch1];
	motor[backRight] = -vexRT[Ch3] + vexRT[Ch1];
}

void armControl(){
	if(vexRT[Btn6U]){
		motor[armLeft] = 127;
		motor[armRight] = -127;
	}
	else if(vexRT[Btn6D]){
		motor[armLeft] = -127;
		motor[armRight] = 127;
	}
	else{
		motor[armRight] = 0;
		motor[armLeft] = 0;
	}

	//motor[armLeft] = vexRT[Ch3Xmtr2];
	//motor[armRight] = -vexRT[Ch3Xmtr2];
}

void intakeSucc(){

	if(vexRT[Btn5U]){
		motor[intakeLeft] = 127;
		motor[intakeRight] = -127;
	}
	else if(vexRT[Btn5D]){
		motor[intakeLeft] = -127;
		motor[intakeRight] = 127;
	}
	else{
		motor[intakeRight] = 0;
		motor[intakeLeft] = 0;
	}
	//motor[intakeLeft] = vexRT[Ch2Xmtr2];
	//motor[intakeRight] = -vexRT[Ch2Xmtr2];
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	//Main Loop
  while (true)
  {
  	arcadeDrive();
		armControl();
		intakeSucc();

    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
  }
}
