#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           frontLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           baseRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           baseLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

	bool clawClosed = true;
	while(true){

			motor[frontLeft] = (vexRT[Ch3] + vexRT[Ch1]);
			motor[frontRight] = (-1*vexRT[Ch3] + vexRT[Ch1]);


			motor[baseLeft] = (vexRT[Ch4Xmtr2]); // left joystick for mobile base
			motor[baseRight] = (vexRT[Ch4Xmtr2]);

			motor[arm] = (vexRT[Ch2Xmtr2]); // right joystick for arm

			//motor[clawLeft] = (vexRT[Ch3Xmtr2]);
			//motor[clawRight] = (vexRT[Ch3Xmtr2]);
			int closedButton = vexRT[Btn6DXmtr2], openButton = vexRT[Btn5DXmtr2];
			if (openButton == 1){
				motor[claw] = -60;
				// open claw (run claw motors)
				clawClosed = false;
			}
			else if (closedButton == 1){
				// close claw
				motor[claw] = 127;

				clawClosed = true;
			}

			else if (clawClosed == true){
				motor[claw] = 15;

			}

			else {
				motor[claw] = 0;
			}

		}
}
