#pragma config(Motor,  port1,           armRight,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           baseRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           baseLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           clawRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          armLeft,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	//Initialization
	clearTimer(T1);
	motor[clawLeft] = 5;
	motor[clawRight] = 5;

	while(time1[T1] < 2000){
		motor[armLeft] = 127;
		motor[armRight] = -127;
		if (time1[T1] > 600){
			motor[baseLeft] = -127;
			motor[baseRight] = 127;
		}
		if (time1[T1] > 1600){
			motor[armLeft] = 5;
			motor[armRight] = -5;
		}
		if (time1[T1] > 1400){
			motor[backRight] = -127;
			motor[backLeft] = 127;
			motor[frontRight] = -127;
			motor[frontLeft] = 127;
		}
	}

	// Moving forward
	clearTimer(T1);
	while (time1[T1] < 900){
		motor[backRight] = -127;
		motor[backLeft] = 127;
		motor[frontRight] = -127;
		motor[frontLeft] = 127;
	}

	// Picking up mobile base

	clearTimer(T1);
	while (time1[T1] < 1100){
		motor[baseLeft] = 127;
		motor[baseRight] = -127;
		if (time1[T1] > 600) {
			motor[backRight] = -0;
			motor[backLeft] = 0;
			motor[frontRight] = -0;
			motor[frontLeft] = 0;
	}
}
/*
	while (time1[T1] < 500){
		if (time1[T1] % 10 == 0){
			motor[backRight] = 	motor[backRight] + 2;
			motor[backLeft] = 	motor[backLeft] - 2;
			motor[frontRight] = 	motor[backLeft] + 2;
			motor[frontLeft] = 	motor[backLeft] - 2;
		}
	}
	motor[backRight] = 	0;
	motor[backLeft] = 	0;
	motor[frontRight] = 0;
	motor[frontLeft] = 	0;
	// Turning
	clearTimer(T1);
	while (time1[T1] < 500){
		if (time1[T1] % 10 == 0){
			motor[backRight] = motor[backRight] + 2;
			motor[backLeft] = motor[backRight] - 2;
			motor[frontRight] = motor [frontRight] + 2;
			motor[frontLeft] = motor[frontLeft] - 2;
		}
	}

	motor[backRight] = 127;
	motor[backLeft] = -127;
	motor[frontRight] = 127;
	motor[frontLeft] = -127;

	clearTimer(T1);
	while (time1[T1] < 800){
		motor[backRight] = 127;
		motor[backLeft] = -127 + 80;
		motor[frontRight] = 127;
		motor[frontLeft] = -127 + 80;
	}
	clearTimer(T1);
	while (time1[T1] < 1200){
		motor[backRight] = 127;
		motor[backLeft] = 127;
		motor[frontRight] = 127;
		motor[frontLeft] = 127;
	}
	clearTimer(T1);
*/
/*
	// Moving forward while moving arm up
	while (time1[T1] < 500){
		motor[armLeft] = -50; // move arm down
		motor[armRight] = 50;
		motor[backRight] = -127; //movement
		motor[backLeft] = 127;
		motor[frontRight] = -127;
		motor[frontLeft] = 127;
	}
	clearTimer(T1);
	// moving forward while dropping cone
	while (time1[T1] < 500){
		motor[armLeft] = -20; // apply constant pressure to stabilize arm
		motor[armRight] = 20;
		motor[backRight] = -127; // movement
		motor[backLeft] = 127;
		motor[frontRight] = -127;
		motor[frontLeft] = 127;
		motor[clawLeft] = -127; // drop cone
		motor[clawRight] = -127;
	}
	motor[clawLeft] = 0; // drop cone
	motor[clawRight] = 0;

	// Dropping mobile base
	clearTimer(T1);
	while (time1[T1] < 700){
	motor[baseLeft] = 127;
	motor[baseRight] = -127;
	}
	while (time1[T1] < 1000){
	motor[backRight] = 127;
	motor[backLeft] = -127;
	motor[frontRight] = 127;
	motor[frontLeft] = -127;
	}
	*/
}
