#pragma config(Motor,  port1,           backLeft,      tmotorNone, openLoop)
#pragma config(Motor,  port2,           claw,          tmotorNone, openLoop)
#pragma config(Motor,  port3,           armLeft,       tmotorNone, openLoop)
#pragma config(Motor,  port4,           armRight,      tmotorNone, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorNone, openLoop)
#pragma config(Motor,  port6,           backRight,     tmotorNone, openLoop)
#pragma config(Motor,  port7,           armRight,      tmotorNone, openLoop)
#pragma config(Motor,  port8,           armLeft,       tmotorNone, openLoop)
#pragma config(Motor,  port9,           base,          tmotorNone, openLoop)
#pragma config(Motor,  port10,          backRight,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	//Initialization
	clearTimer(T1);
	motor[claw] = 5;


	while(time1[T1] < 2000){
		motor[armLeft] = 127;
		motor[armRight] = -127;
		if (time1[T1] > 600){
			motor[base] = -127;

		}
		if (time1[T1] > 1600){
			motor[armLeft] = 5;
			motor[armRight] = -5;
		}
		if (time1[T1] > 1500){
			motor[backRight] = -127;
			motor[backLeft] = 127;

		}
	}
	// Moving forward
	clearTimer(T1);
	while (time1[T1] < 600){
		motor[backRight] = -127;
		motor[backLeft] = 127;

	}

	// Picking up mobile base

	clearTimer(T1);
	while (time1[T1] < 1100){
		motor[base] = 127;

	}

	while (time1[T1] < 500){
		if (time1[T1] % 10 == 0){
			motor[backRight] = 	motor[backRight] + 2;
			motor[backLeft] = 	motor[backLeft] - 2;

		}
	}
	motor[backRight] = 	0;
	motor[backLeft] = 	0;

	// Turning
	clearTimer(T1);
	while (time1[T1] < 500){
		if (time1[T1] % 10 == 0){
			motor[backRight] = motor[backRight] + 2;
			motor[backLeft] = motor[backRight] - 2;

		}
	}

	motor[backRight] = 127;
	motor[backLeft] = -127;


	clearTimer(T1);
	while (time1[T1] < 800){
		motor[backRight] = 127;
		motor[backLeft] = -127 + 80;

	}
	clearTimer(T1);
	while (time1[T1] < 1200){
		motor[backRight] = 127;
		motor[backLeft] = 127;

	}
	clearTimer(T1);
/*
	// Moving forward while moving arm up
	while (time1[T1] < 500){
		motor[armLeft] = -50; // move arm down
		motor[armRight] = 50;
		motor[backRight] = -127; //movement
		motor[backLeft] = 127;

	}
	clearTimer(T1);
	// moving forward while dropping cone
	while (time1[T1] < 500){
		motor[armLeft] = -20; // apply constant pressure to stabilize arm
		motor[armRight] = 20;
		motor[backRight] = -127; // movement
		motor[backLeft] = 127;
		motor[claw] = -127; // drop cone

	}
	motor[clawLeft] = 0; // drop cone
	motor[clawRight] = 0;

	// Dropping mobile base
	clearTimer(T1);
	while (time1[T1] < 700){
		motor[base] = -127;

	}
	// Reversing
	while (time1[T1] < 1000){
		motor[backRight] = 127;
		motor[backLeft] = -127;

	}
	*/
}
