#pragma config(Motor,  port1,           backRight,     tmotorNone, openLoop)
#pragma config(Motor,  port2,           armRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           clawLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           clawRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           baseRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           baseLeft,      tmotorNone, openLoop)
#pragma config(Motor,  port9,           armLeft,       tmotorNone, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Who are you?? Ur code is very nice

task main()
{
	while(true){

			bool clawClosed = true;
			motor[frontLeft] = (vexRT[Ch2] - vexRT[Ch4]);
			motor[backLeft] = (vexRT[Ch2] - vexRT[Ch4]);
			motor[frontRight] = (-1*vexRT[Ch2] - vexRT[Ch4]);
			motor[backRight] = (-1*vexRT[Ch2] - vexRT[Ch4]);

			motor[baseLeft] = (vexRT[Ch4Xmtr2]); // left joystick for mobile base
			motor[baseRight] = (vexRT[Ch4Xmtr2]);

			motor[armLeft] = (vexRT[Ch2Xmtr2]); // right joystick for arm
			motor[armRight] = (vexRT[Ch2Xmtr2]);
			//motor[clawLeft] = (vexRT[Ch3Xmtr2]);
			//motor[clawRight] = (vexRT[Ch3Xmtr2]);
			int closedButton = vexRT[Btn6DXmtr2], openButton = vexRT[Btn5DXmtr2];
			if (openButton == 1){
				motor[clawLeft] = -127;
				motor[clawRight] = -127;
				// open claw (run claw motors)
				clawClosed = false;
			}
			else if (closedButton == 1){
				// close claw
				motor[clawLeft] = 127;
				motor[clawRight] = 127;
				clawClosed = true;
			}

			if (clawClosed == true){
				motor[clawLeft] = 5;
				motor[clawRight] = 5;
			}
	}
}
